var Handlebars = require('handlebars/runtime')['default'];
var ClientHandlebars = require('handlebars');
var App = require('app');

//  you can assign helpers explicitly to one type of compilation
// runtime is used for precompilation
// for compilation on client side (browser) you can use  normal version
// you can freely mix those of types when needed (eg. form templates generated by server)

Handlebars.registerHelper('url', function(value) {
	return App.Config.getValue('urlRoot') + value;
});

ClientHandlebars.registerHelper('url', function(value) {
	return App.Config.getValue('urlRoot') + value;
});
